"""update category model

Revision ID: 743c4223aa05
Revises: db3dd0f9f518
Create Date: 2026-02-10 14:56:19.569743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743c4223aa05'
down_revision: Union[str, Sequence[str], None] = 'db3dd0f9f518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'categories', ['description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
