"""update role model

Revision ID: db3dd0f9f518
Revises: 9d74427e4c11
Create Date: 2026-02-10 11:12:03.908280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3dd0f9f518'
down_revision: Union[str, Sequence[str], None] = '9d74427e4c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('roles', sa.Column('created_ad', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'created_ad')
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
